### ISSUE TITLE
--obs-keys fails to read oscrc on Leap 15

### ISSUE THREAD

**Issue by sriemer** [openSUSE/mkdud#17]
With Leap 15 the location of the oscrc config file changed from `~/.oscrc` to `~/.config/osc/oscrc` the workaround is to set a symlink at the old location.

**Comment by wfeldt** [comment]
On my Leap 15.0 osc reads ~/.oscrc and this is also the only location osc docs mention.

**Comment by wfeldt** [comment]
https://github.com/openSUSE/mkdud/pull/18, please check the pr

**Comment by sriemer** [comment]
Yes, the problem is if not having a `~/.oscrc` config, then Leap 15 osc creates it at `~/.config/osc/oscrc`. Thanks.
