### ISSUE TITLE
PR #18 is faulty on Leap 42.3

### ISSUE THREAD

**Issue by sriemer** [openSUSE/mkdud#19]
I just tried mkdud --create with `--obs-keys` on Leap 42.3 only having `~/.oscrc` and I get the following error:
```
Can't use an undefined value as a symbol reference at /usr/bin/mkdud line 252.
```
https://github.com/openSUSE/mkdud/blob/61ece398d3d42f60b78323ca6d6f0e75b86cc9aa/mkdud#L252

At the previous commit this is working.

**Comment by sriemer** [comment]
Please fix the commit in PR #18 so that it works for both variants. TIA

**Comment by wfeldt** [comment]
fixed with https://github.com/openSUSE/mkdud/pull/22

**Comment by sriemer** [comment]
I can confirm that this is fixed with the PR. Thanks!
